### ISSUE TITLE
WorkflowService API retry options are not set correctly

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#317] opened 2019-06-06 20:24 UTC
For example EntityNotExistsError should not be retried when completing decision:

```
13:20:44.007 [null HelloWorldTaskList : 1] WARN  c.u.cadence.internal.common.Retryer - Retrying after failure
com.uber.cadence.EntityNotExistsError: Workflow execution already completed.
	at com.uber.cadence.WorkflowService$RespondDecisionTaskCompleted_result$RespondDecisionTaskCompleted_resultStandardScheme.read(WorkflowService.java:17056)
	at com.uber.cadence.WorkflowService$RespondDecisionTaskCompleted_result$RespondDecisionTaskCompleted_resultStandardScheme.read(WorkflowService.java:17015)
	at com.uber.cadence.WorkflowService$RespondDecisionTaskCompleted_result.read(WorkflowService.java:16914)
	at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:81)
	at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:67)
	at com.uber.tchannel.messages.ThriftSerializer.decodeBody(ThriftSerializer.java:72)
	at com.uber.tchannel.messages.Serializer.decodeBody(Serializer.java:49)
	at com.uber.tchannel.messages.EncodedResponse.getBody(EncodedResponse.java:85)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.respondDecisionTaskCompleted(WorkflowServiceTChannel.java:879)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$RespondDecisionTaskCompleted$10(WorkflowServiceTChannel.java:865)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:492)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.RespondDecisionTaskCompleted(WorkflowServiceTChannel.java:863)
	at com.uber.cadence.internal.worker.WorkflowWorker$TaskHandlerImpl.lambda$sendReply$0(WorkflowWorker.java:273)
	at com.uber.cadence.internal.common.Retryer.lambda$retry$0(Retryer.java:75)
	at com.uber.cadence.internal.common.Retryer.retryWithResult(Retryer.java:93)
	at com.uber.cadence.internal.common.Retryer.retry(Retryer.java:72)
	at com.uber.cadence.internal.worker.WorkflowWorker$TaskHandlerImpl.sendReply(WorkflowWorker.java:273)
	at com.uber.cadence.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:242)
	at com.uber.cadence.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:221)
	at com.uber.cadence.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by mfateev** [comment] 2019-06-06 20:25
Somehow Related https://github.com/uber/cadence-java-client/issues/258

**Comment by meiliang86** [comment] 2019-06-14 21:48
Duplicate of #247, which is already fixed in the latest client.

**Closed by meiliang86** 2019-06-14 21:48 UTC
